{{-- Shared letterhead for every Finance PDF report — logo on the left,
     school identity block to its right (matches the school's own printed
     fee-schedule letterhead), same table-cell technique already used in
     resources/views/pdf/sf10.blade.php.
     Expects: $schoolLogoBase64, $schoolName, $reportTitle,
     $dateRangeLabel (string or null), $generatedBy, $generatedAt (Carbon) --}}
<div class="fin-header">
    <div class="fin-header-inner">
        <div class="fin-header-logo">
            @if($schoolLogoBase64)
                <img src="{{ $schoolLogoBase64 }}" alt="">
            @endif
        </div>
        <div class="fin-header-text">
            <div class="fin-school-name">{{ strtoupper($schoolName) }}</div>
            <div class="fin-school-addr">General Tinio IEMELIF Church</div>
            <div class="fin-school-addr">Poblacion Central, General Tinio, Nueva Ecija.</div>
        </div>
    </div>
</div>
<div class="fin-title-bar">
    <div class="fin-report-title">{{ $reportTitle }}</div>
    <div class="fin-title-divider"></div>
    @if(!empty($dateRangeLabel))
        <div class="fin-report-range">{{ $dateRangeLabel }}</div>
    @endif
</div>
<div class="fin-meta-row">
    <span>Generated by: {{ $generatedBy }}</span>
    <span>Generated on: {{ $generatedAt->format('M d, Y g:i A') }}</span>
</div>
