
<div class="fin-header">
    <div class="fin-header-inner">
        <div class="fin-header-logo">
            <?php if($schoolLogoBase64): ?>
                <img src="<?php echo e($schoolLogoBase64); ?>" alt="">
            <?php endif; ?>
        </div>
        <div class="fin-header-text">
            <div class="fin-school-name"><?php echo e(strtoupper($schoolName)); ?></div>
            <div class="fin-school-addr">General Tinio IEMELIF Church</div>
            <div class="fin-school-addr">Poblacion Central, General Tinio, Nueva Ecija.</div>
        </div>
    </div>
</div>
<div class="fin-title-bar">
    <div class="fin-report-title"><?php echo e($reportTitle); ?></div>
    <div class="fin-title-divider"></div>
    <?php if(!empty($dateRangeLabel)): ?>
        <div class="fin-report-range"><?php echo e($dateRangeLabel); ?></div>
    <?php endif; ?>
</div>
<div class="fin-meta-row">
    <span>Generated by: <?php echo e($generatedBy); ?></span>
    <span>Generated on: <?php echo e($generatedAt->format('M d, Y g:i A')); ?></span>
</div>
<?php /**PATH C:\Users\ron28\Desktop\ILC SYSTEM\ilc-website-system\resources\views/pdf/shared/_letterhead.blade.php ENDPATH**/ ?>